using System.Net;

namespace StockSense.Web.Helpers;

public static class QuotationEmailTemplate
{
    public static string Build(string customerEmail, decimal grandTotal, int itemCount)
    {
        var safeEmail = WebUtility.HtmlEncode(customerEmail);
        var safeTotal = WebUtility.HtmlEncode(grandTotal.ToString("N2"));
        var safeItemCount = WebUtility.HtmlEncode(itemCount.ToString());

        return $$"""
            <!doctype html>
            <html lang="en">
            <body style="margin:0;padding:0;background-color:#f4f4f5;font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,Helvetica,Arial,sans-serif;color:#18181b;">
                <table role="presentation" width="100%" cellspacing="0" cellpadding="0" border="0" style="width:100%;background-color:#f4f4f5;">
                    <tr>
                        <td align="center" style="padding:40px 16px;">
                            <table role="presentation" width="520" cellspacing="0" cellpadding="0" border="0" style="width:100%;max-width:520px;background-color:#ffffff;border:1px solid #e4e4e7;border-radius:10px;overflow:hidden;box-shadow:0 4px 12px rgba(0,0,0,0.08);">
                                <tr><td style="height:6px;background-color:#dc2626;font-size:0;line-height:0;">&nbsp;</td></tr>
                                <tr>
                                    <td style="padding:32px;">
                                        <p style="margin:0 0 18px;text-align:center;color:#dc2626;font-size:13px;font-weight:800;letter-spacing:1.6px;text-transform:uppercase;">SAP SHOP</p>
                                        <h1 style="margin:0;text-align:center;color:#09090b;font-size:25px;line-height:1.25;font-weight:700;">Your build quotation</h1>
                                        <p style="margin:8px 0 0;text-align:center;color:#71717a;font-size:15px;line-height:1.5;">Please find attached your custom build quotation with pricing details.</p>

                                        <div style="border-top:1px solid #e4e4e7;margin:26px 0;"></div>

                                        <table role="presentation" width="100%" cellspacing="0" cellpadding="0" border="0" style="width:100%;background-color:#fef2f2;border:1px solid #fecaca;border-radius:8px;">
                                            <tr>
                                                <td style="padding:18px 20px;">
                                                    <p style="margin:0 0 5px;color:#991b1b;font-size:11px;font-weight:700;letter-spacing:1px;text-transform:uppercase;">Quotation summary</p>
                                                    <p style="margin:0;color:#18181b;font-size:14px;line-height:1.5;">{{safeItemCount}} part(s) &middot; <strong style="font-size:16px;">₱{{safeTotal}}</strong></p>
                                                </td>
                                            </tr>
                                        </table>

                                        <table role="presentation" width="100%" cellspacing="0" cellpadding="0" border="0" style="width:100%;margin-top:20px;background-color:#fafafa;border:1px solid #e4e4e7;border-radius:8px;">
                                            <tr>
                                                <td style="padding:16px 18px;">
                                                    <p style="margin:0;color:#27272a;font-size:13px;font-weight:700;">PDF quotation attached</p>
                                                    <p style="margin:4px 0 0;color:#71717a;font-size:12px;line-height:1.5;">The attachment contains the complete parts list with unit pricing and totals.</p>
                                                </td>
                                            </tr>
                                        </table>

                                        <p style="margin:26px 0 0;color:#52525b;font-size:14px;line-height:1.6;">
                                            Regards,<br><strong style="color:#18181b;">Sap Shop (Motor Parts &amp; Accessories)</strong>
                                        </p>
                                    </td>
                                </tr>
                                <tr>
                                    <td style="padding:17px 32px;background-color:#fafafa;border-top:1px solid #e4e4e7;text-align:center;color:#a1a1aa;font-size:11px;line-height:1.5;">
                                        This quotation was generated by SAP SHOP inventory management.
                                    </td>
                                </tr>
                            </table>
                        </td>
                    </tr>
                </table>
            </body>
            </html>
            """;
    }
}
