using QuestPDF.Fluent;
using QuestPDF.Helpers;
using QuestPDF.Infrastructure;
using StockSense.Application.DTOs;
namespace StockSense.Infrastructure.Services;

public class DocumentService
{
    public byte[] GenerateOrderSlipPdf(OrderSlipDto slipDto)
    {
        QuestPDF.Settings.License = LicenseType.Community;

        return Document.Create(container =>
        {
            container.Page(page =>
            {
                page.Margin(1, Unit.Inch);

                page.Header().Column(header =>
                {
                    header.Item().Text($"Purchase Order: {slipDto.OrderSlipNumber}")
                        .FontSize(18).SemiBold().FontColor(Colors.Blue.Medium);
                    header.Item().PaddingTop(3).Text(t =>
                    {
                        t.Span("Supplier: ").SemiBold();
                        t.Span(slipDto.SupplierName);
                    });
                    header.Item().Text(t =>
                    {
                        t.Span("Date: ").SemiBold();
                        t.Span($"{slipDto.GeneratedAt:MMMM dd, yyyy}");
                    });
                    header.Item().Text(t =>
                    {
                        t.Span("Expected Delivery: ").SemiBold();
                        t.Span(slipDto.ExpectedDeliveryDate?.ToString("MMMM dd, yyyy") ?? "Not specified");
                    });
                });

                page.Content().PaddingTop(15).Table(table =>
                {
                    table.ColumnsDefinition(columns =>
                    {
                        columns.RelativeColumn(4);
                        columns.RelativeColumn(1);
                    });

                    table.Header(header =>
                    {
                        header.Cell().BorderBottom(1).BorderColor(Colors.Grey.Lighten2).PaddingBottom(5).Text("Product").SemiBold();
                        header.Cell().BorderBottom(1).BorderColor(Colors.Grey.Lighten2).PaddingBottom(5).Text("Qty").SemiBold().AlignRight();
                    });

                    foreach (var item in slipDto.Items)
                    {
                        var qty = item.OrderedQuantity == 0 ? item.Quantity : item.OrderedQuantity;
                        table.Cell().PaddingVertical(4).Text($"{item.ProductName} ({item.Brand})");
                        table.Cell().PaddingVertical(4).Text(qty.ToString()).AlignRight();
                    }
                });

                if (!string.IsNullOrWhiteSpace(slipDto.Remarks))
                {
                    page.Content().PaddingTop(20).Text(t =>
                    {
                        t.Span("Remarks: ").SemiBold();
                        t.Span(slipDto.Remarks);
                    });
                }

                page.Footer()
                    .AlignCenter()
                    .Text(x =>
                    {
                        x.DefaultTextStyle(t => t.FontSize(9).FontColor(Colors.Grey.Medium));
                        x.Span("Generated by StockSense - Page ");
                        x.CurrentPageNumber();
                    });
            });
        }).GeneratePdf();
    }
}