using QuestPDF.Fluent;
using QuestPDF.Helpers;
using QuestPDF.Infrastructure;
using StockSense.Application.DTOs;
namespace StockSense.Infrastructure.Services;

public class DocumentService
{
    public byte[] GenerateOrderSlipPdf(OrderSlipDto slipDto)
    {
        // Note: For production, it's best practice to move this license setup 
        // to your Web project's Program.cs, but it works fine here for now.
        QuestPDF.Settings.License = LicenseType.Community;

        return Document.Create(container =>
        {
            container.Page(page =>
            {
                page.Margin(1, Unit.Inch);
                
                page.Header()
                    .Text($"Order Slip: {slipDto.SlipNumber}")
                    .FontSize(20)
                    .SemiBold()
                    .FontColor(Colors.Blue.Medium);

                page.Content().Column(col =>
                {
                    col.Item().Text($"Supplier: {slipDto.SupplierName}");
                    col.Item().Text($"Date: {slipDto.DateGenerated:MM/dd/yyyy}");
                    
                    col.Item().PaddingTop(10).Table(table =>
                    {
                        table.ColumnsDefinition(columns => {
                            columns.RelativeColumn(3); // Product Name column gets 75% width
                            columns.RelativeColumn(1); // Quantity column gets 25% width
                        });
                        
                        table.Header(header => {
                            header.Cell().BorderBottom(1).BorderColor(Colors.Grey.Lighten2).PaddingBottom(5).Text("Product").SemiBold();
                            header.Cell().BorderBottom(1).BorderColor(Colors.Grey.Lighten2).PaddingBottom(5).Text("Quantity").SemiBold();
                        });
                        
                        foreach (var item in slipDto.Items)
                        {
                            table.Cell().PaddingVertical(2).Text($"{item.ProductName} ({item.Brand})");
                            table.Cell().PaddingVertical(2).Text(item.Quantity.ToString());
                        }
                    });
                });
                
                page.Footer()
                    .AlignCenter()
                    .Text(x => {
                        x.Span("Generated by Sap Shop Inventory System - Page ");
                        x.CurrentPageNumber();
                    });
            });
        }).GeneratePdf();
    }

    public byte[] GenerateTransactionReceiptPdf(ReceiptDto receipt)
    {
        QuestPDF.Settings.License = LicenseType.Community;

        var subtotal = receipt.TotalAmount + receipt.DiscountAmount;

        return Document.Create(container =>
        {
            container.Page(page =>
            {
                page.ContinuousSize(80, Unit.Millimetre);
                page.Margin(5, Unit.Millimetre);
                page.Content().Column(col =>
                {
                    col.Spacing(2);
                    col.Item().AlignCenter().Text("SAPSHOP MOTORCYCLE PARTS AND ACCESSORIES SHOP").FontSize(9).SemiBold();
                    col.Item().AlignCenter().Text("CHIA D. CUNANAN - Prop.").FontSize(8);
                    col.Item().AlignCenter().Text("B1, L70, Model Community, Pio, 2008 Porac, Pampanga").FontSize(8);
                    col.Item().PaddingVertical(3).AlignCenter().Text("SALES TRANSACTION SUMMARY").FontSize(9).SemiBold();
                    col.Item().Text($"Date: {receipt.TransactionDate:MM/dd/yyyy HH:mm}").FontSize(8);
                    col.Item().Text($"Transaction No: {receipt.InvoiceNumber}").FontSize(8);
                    col.Item().Text($"Payment: {receipt.PaymentMethod}").FontSize(8);
                    if (!string.IsNullOrWhiteSpace(receipt.ReferenceNumber))
                        col.Item().Text($"Reference: {receipt.ReferenceNumber}").FontSize(8);
                    col.Item().PaddingVertical(3).LineHorizontal(0.5f).LineColor(Colors.Grey.Darken1);
                    foreach (var item in receipt.Items)
                    {
                        col.Item().Text(item.ProductName).FontSize(8).SemiBold();
                        col.Item().Row(row =>
                        {
                            row.RelativeItem().Text($"{item.Quantity} x P{item.UnitPrice:N2}").FontSize(8);
                            row.ConstantItem(42).AlignRight().Text(item.LineTotal.ToString("N2")).FontSize(8);
                        });
                    }
                    col.Item().PaddingVertical(3).LineHorizontal(0.5f).LineColor(Colors.Grey.Darken1);
                    col.Item().Row(row =>
                    {
                        row.RelativeItem().Text("Total Sales:").FontSize(8);
                        row.ConstantItem(42).AlignRight().Text(subtotal.ToString("N2")).FontSize(8);
                    });
                    if (receipt.DiscountAmount > 0)
                    {
                        col.Item().Row(row =>
                        {
                            row.RelativeItem().Text("Less: Discount:").FontSize(8);
                            row.ConstantItem(42).AlignRight().Text("-" + receipt.DiscountAmount.ToString("N2")).FontSize(8);
                        });
                    }
                    col.Item().PaddingTop(3).Row(row =>
                    {
                        row.RelativeItem().Text("TOTAL AMOUNT:").FontSize(11).SemiBold();
                        row.ConstantItem(42).AlignRight().Text($"P{receipt.TotalAmount:N2}").FontSize(11).SemiBold();
                    });
                    if (!string.IsNullOrWhiteSpace(receipt.Remarks))
                        col.Item().PaddingTop(3).Text($"Remarks: {receipt.Remarks}").FontSize(8);
                    col.Item().PaddingTop(6).AlignCenter().Text(x =>
                    {
                        x.Span("FOR RECORD-KEEPING AND FUTURE REFERENCE ONLY\n").SemiBold().FontSize(7);
                        x.Span("This document is not an official receipt or sales invoice.\n").FontSize(7);
                        x.Span("Generated by Sap Shop Inventory System").FontSize(7);
                    });
                });
            });
        }).GeneratePdf();
    }
}